# Generated by Django 5.2.7 on 2025-10-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(verbose_name='Detalhes da Tarefa')),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('DOING', 'Doing'), ('DONE', 'Done')])),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')])),
                ('dueDate', models.DateField()),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.projects')),
            ],
        ),
    ]
